# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\anneb\Documents\GAO_PIPELINE\GAOLIB\gaolib\ui\constraintinfopairingwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtGui import QAction


class Ui_ConstraintForm(object):
    def setupUi(self, ConstraintForm):
        ConstraintForm.setObjectName("ConstraintForm")
        ConstraintForm.resize(255, 163)
        ConstraintForm.setStyleSheet(
            "QMainWindow{\n"
            "    color: #b1b1b1;\n"
            "    background-color: #3c3c3c;\n"
            "}\n"
            "\n"
            "QWidget{\n"
            "            background-color: #444;\n"
            "            color: white;\n"
            "}\n"
            "\n"
            "QScrollArea{\n"
            "            background-color: #444;\n"
            "            color: white;\n"
            "            border: 0px solid #222;\n"
            "            \n"
            "}\n"
            "\n"
            "QListWidget{\n"
            "            background-color: #444;\n"
            "            color: white;\n"
            "            border: 0px solid #222;\n"
            "            \n"
            "}\n"
            "\n"
            "QStatusBar{\n"
            "    color: white;\n"
            "}\n"
            "\n"
            "QMenuBar {\n"
            "            background-color: #444;\n"
            "}\n"
            "\n"
            "QMenuBar::item {\n"
            "            background-color: #444;\n"
            "            color: rgb(255,255,255);\n"
            "}\n"
            "\n"
            "QMenuBar::item::selected {\n"
            "            background-color: rgb(30,30,30);\n"
            "}\n"
            "\n"
            "QMenu {\n"
            "            background-color: #3c3c3c;\n"
            "}\n"
            "\n"
            "QMenu::item {\n"
            "            background-color: #3c3c3c;\n"
            "            color: rgb(255,255,255);\n"
            "}\n"
            "\n"
            "QMenu::item::selected {\n"
            "            background-color: rgb(30,30,30);\n"
            "}\n"
            "\n"
            "QDialog\n"
            "{\n"
            "    color: #b1b1b1;\n"
            "    background-color: #3c3c3c;\n"
            "}\n"
            "\n"
            "QTabWidget QWidget\n"
            "{\n"
            "    background: #444;\n"
            "}\n"
            "\n"
            "#page, #page_2, #page_3 {\n"
            "    background-color: #3c3c3c;\n"
            "}\n"
            "\n"
            "QGroupBox {\n"
            "     color: #628CB2;\n"
            "     border: 1px solid #222;\n"
            "     border-radius: 5px;\n"
            "     margin-top: 1ex; /* leave space at the top for the title */\n"
            "}\n"
            "\n"
            "QGroupBox::title {\n"
            "     subcontrol-origin: margin;\n"
            "     subcontrol-position: top center; /* position at the top center */\n"
            "     padding: 0 3px;\n"
            "     background-color: QLinearGradient( x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 #333, stop: 1 #3c3c3c);\n"
            "}\n"
            "\n"
            "QHeaderView::section:vertical\n"
            "{\n"
            "    margin-bottom: 4px;\n"
            "    border: 1px solid;\n"
            "}\n"
            "\n"
            "QLineEdit\n"
            "{\n"
            "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
            "    padding: 1px;\n"
            "    border-style: solid;\n"
            "    border: 1px solid #4D5056;\n"
            "    border-radius: 5;\n"
            "    color: #b1b1b1;\n"
            "}\n"
            "\n"
            "QPushButton\n"
            "{\n"
            "    color: #b1b1b1;\n"
            "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
            "    border-width: 1px;\n"
            "    border-color: #555555;\n"
            "    border-style: solid;\n"
            "    border-radius: 5;\n"
            "    padding: 3px;\n"
            "    padding-left: 5px;\n"
            "    padding-right: 5px;\n"
            "    outline: 0;\n"
            "}\n"
            "\n"
            "QPushButton:pressed\n"
            "{\n"
            "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #3d3d3d, stop: 0.1 #3b3b3b, stop: 0.5 #393939, stop: 0.9 #383838, stop: 1 #353535);\n"
            "}\n"
            "\n"
            "QComboBox\n"
            "{\n"
            "    color: #b1b1b1;\n"
            "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
            "    border: 1px outset #4D5056;\n"
            "    border-radius: 3px;\n"
            "    padding: 1px 3px 1px 5px;\n"
            "    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #097ace, stop: 1 #097ace);\n"
            "    combobox-popup: 1;\n"
            "}\n"
            "\n"
            "QComboBox:hover, QPushButton:hover\n"
            "{\n"
            "    border: 1px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #333 , stop: 1 #333);\n"
            "}\n"
            "\n"
            "QComboBox:on\n"
            "{\n"
            "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
            "}\n"
            "\n"
            "QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
            "    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
            "}\n"
            "\n"
            "QComboBox::drop-down\n"
            "{\n"
            "     subcontrol-origin: padding;\n"
            "     subcontrol-position: top right;\n"
            "     border-left-width: 0px;\n"
            "     border-left-color: black;\n"
            "     border-left-style: inset;\n"
            "     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
            "     border-bottom-right-radius: 3px;\n"
            "}\n"
            "\n"
            "QComboBox::down-arrow {\n"
            "     image: url(./icons/arrow.png);\n"
            "}\n"
            "\n"
            "QComboBox QAbstractItemView {\n"
            "    selection-background-color: lightgray;\n"
            "    background-color: #3c3c3c;\n"
            "    border: 1px outset #3c3c3c;\n"
            "}\n"
            "\n"
            "QLabel\n"
            "{\n"
            "    color: #b1b1b1;\n"
            "    background-color: transparent;\n"
            "}\n"
            "\n"
            "QSplitter::handle:vertical\n"
            "{\n"
            "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #494949, stop:1 #6f6f6f);\n"
            "    height: 2px;\n"
            "}\n"
            "\n"
            "QSplitter::handle:horizontal\n"
            "{\n"
            "    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #494949, stop:1 #6f6f6f);\n"
            "    width: 2px;\n"
            "}\n"
            "\n"
            "QToolBox {\n"
            "    background: #444;\n"
            "}\n"
            "\n"
            "QToolBox QScrollArea>QWidget>QWidget\n"
            "{\n"
            "    background: #444;\n"
            "}\n"
            "\n"
            "QToolBox::tab {\n"
            "   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #E1E1E1, stop: 0.4 #DDDDDD, stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
            "   color: darkgray;\n"
            "}\n"
            "\n"
            "QToolBox::tab:selected {\n"
            "    color: black;\n"
            "}\n"
            "\n"
            "QTabWidget::pane { /* The tab widget frame */\n"
            "    border: 1px solid #333;\n"
            "    background-color: #3c3c3c;\n"
            "}\n"
            "\n"
            "QTabBar::tab {\n"
            "    background: #3a3a3a;\n"
            "    border: 1px solid #222;\n"
            "    border-bottom-color: #444; /* same as the pane color */\n"
            "    min-width: 8ex;\n"
            "    border-top-left-radius: 2px;\n"
            "    border-top-right-radius: 2px;\n"
            "    padding: 3px;\n"
            "}\n"
            "\n"
            "\n"
            "QTabBar::tab:selected, QTabBar::tab:hover {\n"
            "    background: #444;\n"
            "    border-bottom-color: #444; /* same as the pane color */\n"
            "    color: white;\n"
            "}\n"
            "\n"
            "QTabBar::tab:!selected {\n"
            "    margin-top: 2px; /* make non-selected tabs look smaller */\n"
            "}\n"
            "\n"
            "QPlainTextEdit {\n"
            "    background-color: #111;\n"
            "}"
        )
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ConstraintForm)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(ConstraintForm)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.applyWidget = QtWidgets.QWidget(self.groupBox)
        self.applyWidget.setObjectName("applyWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.applyWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_10 = QtWidgets.QLabel(self.applyWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.applyWidget)
        font = QtGui.QFont()
        font.setWeight(QtGui.QFont.Bold)
        font.setLegacyWeight(75)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 5)
        self.applyTargetLabel = QtWidgets.QLabel(self.applyWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setLegacyWeight(50)
        self.applyTargetLabel.setFont(font)
        self.applyTargetLabel.setStyleSheet("color:rgb(255, 255, 255)")
        self.applyTargetLabel.setObjectName("applyTargetLabel")
        self.gridLayout_5.addWidget(self.applyTargetLabel, 4, 1, 1, 1)
        self.applyObjectLabel = QtWidgets.QLabel(self.applyWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setLegacyWeight(50)
        self.applyObjectLabel.setFont(font)
        self.applyObjectLabel.setStyleSheet("color:rgb(255, 255, 255)")
        self.applyObjectLabel.setObjectName("applyObjectLabel")
        self.gridLayout_5.addWidget(self.applyObjectLabel, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.applyWidget)
        self.label_9.setMinimumSize(QtCore.QSize(50, 0))
        self.label_9.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 2, 0, 1, 1)
        self.applyBoneLabel = QtWidgets.QLabel(self.applyWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setLegacyWeight(50)
        self.applyBoneLabel.setFont(font)
        self.applyBoneLabel.setObjectName("applyBoneLabel")
        self.gridLayout_5.addWidget(self.applyBoneLabel, 2, 3, 1, 1)
        self.applyTargetBoneLabel = QtWidgets.QLabel(self.applyWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setLegacyWeight(50)
        self.applyTargetBoneLabel.setFont(font)
        self.applyTargetBoneLabel.setObjectName("applyTargetBoneLabel")
        self.gridLayout_5.addWidget(self.applyTargetBoneLabel, 4, 3, 1, 1)
        self.gridLayout.addWidget(self.applyWidget, 4, 0, 1, 2)
        self.applyConstraintCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.applyConstraintCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.applyConstraintCheckBox.setObjectName("applyConstraintCheckBox")
        self.gridLayout.addWidget(self.applyConstraintCheckBox, 7, 0, 1, 2)
        self.sourceWidget = QtWidgets.QWidget(self.groupBox)
        self.sourceWidget.setObjectName("sourceWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.sourceWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.boneLabel = QtWidgets.QLabel(self.sourceWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setLegacyWeight(50)
        self.boneLabel.setFont(font)
        self.boneLabel.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.boneLabel.setObjectName("boneLabel")
        self.gridLayout_4.addWidget(self.boneLabel, 1, 2, 1, 1)
        self.sourceObjectLabel = QtWidgets.QLabel(self.sourceWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setLegacyWeight(50)
        self.sourceObjectLabel.setFont(font)
        self.sourceObjectLabel.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.sourceObjectLabel.setObjectName("sourceObjectLabel")
        self.gridLayout_4.addWidget(self.sourceObjectLabel, 1, 1, 1, 1)
        self.targetBoneLabel = QtWidgets.QLabel(self.sourceWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.targetBoneLabel.setFont(font)
        self.targetBoneLabel.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.targetBoneLabel.setObjectName("targetBoneLabel")
        self.gridLayout_4.addWidget(self.targetBoneLabel, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.sourceWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.sourceTargetLabel = QtWidgets.QLabel(self.sourceWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.sourceTargetLabel.setFont(font)
        self.sourceTargetLabel.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.sourceTargetLabel.setObjectName("sourceTargetLabel")
        self.gridLayout_4.addWidget(self.sourceTargetLabel, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.sourceWidget)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.sourceWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setWeight(QtGui.QFont.Bold)
        font.setLegacyWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.label_5.setIndent(-2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.sourceWidget, 0, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(ConstraintForm)
        QtCore.QMetaObject.connectSlotsByName(ConstraintForm)

    def retranslateUi(self, ConstraintForm):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("ConstraintForm", "GroupBox"))
        self.label_10.setText(_translate("ConstraintForm", "Target :"))
        self.label_7.setText(_translate("ConstraintForm", "Apply"))
        self.applyTargetLabel.setText(_translate("ConstraintForm", "TextLabel"))
        self.applyObjectLabel.setText(_translate("ConstraintForm", "TextLabel"))
        self.label_9.setText(_translate("ConstraintForm", "Object :"))
        self.applyBoneLabel.setText(_translate("ConstraintForm", "TextLabel"))
        self.applyTargetBoneLabel.setText(_translate("ConstraintForm", "TextLabel"))
        self.applyConstraintCheckBox.setText(
            _translate("ConstraintForm", "Apply constraint")
        )
        self.boneLabel.setText(_translate("ConstraintForm", "TextLabel"))
        self.sourceObjectLabel.setText(_translate("ConstraintForm", "TextLabel"))
        self.targetBoneLabel.setText(_translate("ConstraintForm", "TextLabel"))
        self.label_3.setText(_translate("ConstraintForm", "Target :"))
        self.sourceTargetLabel.setText(_translate("ConstraintForm", "TextLabel"))
        self.label_4.setText(_translate("ConstraintForm", "Object :"))
        self.label_5.setText(_translate("ConstraintForm", "Source"))
